---
title: Universidade Federal Fluminense <br> Programa de formação de executivos <br> Ciência de dados
lang: pt-br
subtitle: "Disciplina: Visualização de dados"
author: "Marcus Ramalho e Ariel Levy"
language: 
  title-block-author-single: "Professores: "
---


# Aula 3 - Visualização de dados likert e deploy de um projeto QUARTO

<details>

<summary>**Preparando o ambiente - CLIQUE!** </summary>

[CLIQUE AQUI PARA BAIXAR O GIT BASH](https://git-scm.com/downloads)

No git bash, execute os seguintes comandos:

```bash

git config --global user.name "Seu_Nome"

git config --global user.email "Se_email"

```

[CLIQUE AQUI PARA CRIAR UMA CONTA NO GITHUB](https://github.com)

</details>

### Objetivo

1.  Aprender a criar gráficos para visualização de dados do tipo likert
2.  Aprender GIT Básico
3.  Aprender a fazer deploy de um projeto QUARTO no GitHub pages

# Conteúdo:

1.  Visualização de dados do tipo likert - Ariel Levy

2.  GIT Básico - Marcus Ramalho

3.  Deploy de um projeto QUARTO no GitHub pages - Marcus Ramalho



# Tarefas 1

Contribuir com o repositório [dataVizR3]

1. Criar um fork do repositório [dataVizR3](https://github.com/nextmarte/dataVizR3)

2. Clone o seu fork para o seu computador `git clone endereco_do_seu_fork`

3. Adicione o repositorio original como upstream (`git remote add upstream https://github.com/nextmarte/dataVizR3`) - use `git pull upstream main` para atualizar o seu fork com as mudanças do repositório original.

4. Crie uma branch com seu nome completo ex: `git checkout -b seu_nome_completo`

5. Navegue até a pasta tarefas, crie umas pasta com seu nome e coloque o arquivo do dashboard que você criou na aula 2 (caso não tenha feito, crie um arquivo .md com seu nome completo) e faça um `git add.` e `git commit` com a mensagem "Adicionando dashboard de [seu nome]"

6. Faça um commit com a mensagem "Adicionando dashboard de [seu nome]"

7. Faça um push da sua branch(seu_nome_completo) para o seu fork (`git push origin seu_nome_completo`)
8. Faça um pull request da sua branch para a branch main do repositório original usando a interface do GitHub.

# Tarefas 2

Crie e faça deploy de um projeto QUARTO no GitHub pages usando o dashboard que você criou na aula 2 e qualquer outro material que você queira adicionar ou tenha criado durante o curso. Adicione o link do seu projeto no campo atividades do arquivo README.md do repositório [dataVizR3] através de um pull request. 

# Recursos adicionais

[ícones bootstrap](https://icons.getbootstrap.com/)

[ícones fontawesome](https://fontawesome.com/v5.15/icons?d=gallery&p=2)

[ícones material design](https://material.io/resources/icons/?style=baseline)

[ícones flaticon](https://www.flaticon.com/)

[Extensões QUARTO]([httpsquartoknows.com/extensions](https://quarto.org/docs/extensions/listing-filters.html))

# Link para os repositórios das aulas anteriores:

[Aula 1](https://github.com/nextmarte/dataVizR) 

[Aula 2](https://github.com/nextmarte/dataVizR2)